query Categories {
  categories {
    id
    name
    colour
    createdAt
  }
}

query CategoriesWithoutRelationField($where: CategoryWhereInput, $orderBy: [CategoryOrderByWithRelationInput!], $cursor: CategoryWhereUniqueInput, $take: Int, $skip: Int, $distinct: [CategoryScalarFieldEnum!]) {
  categories(where: $where, orderBy: $orderBy, cursor: $cursor, take: $take, skip: $skip, distinct: $distinct) {
    _count {
      products
      purchasedByUsers
      tasks
    }
    createdAt
    id
    name
    colour
  }
}

mutation UpdateOneCategory($data: CategoryUpdateInput!, $where: CategoryWhereUniqueInput!) {
  updateOneCategory(data: $data, where: $where) {
    id
  }
}

mutation DeleteOneCategory($where: CategoryWhereUniqueInput!) {
  deleteOneCategory(where: $where) {
    id
  }
}

query CategoryDataForUpdate($where: CategoryWhereUniqueInput!) {
  category(where: $where) {
    id
    name
    colour
  }
}

query AggregateCategory($where: CategoryWhereInput, $orderBy: [CategoryOrderByWithRelationInput!], $cursor: CategoryWhereUniqueInput) {
  aggregateCategory(where: $where, orderBy: $orderBy, cursor: $cursor) {
    _count {
      _all
    }
  }
}

mutation CreateOneCategory($data: CategoryCreateInput!) {
  createOneCategory(data: $data) {
    name
  }
}