query tasksWithoutrelationalData($where: TaskWhereInput, $orderBy: [TaskOrderByWithRelationInput!], $take: Int) {
  tasks(where: $where, orderBy: $orderBy, take: $take) {
    tags
    slug
    name
    imoji
    id
  }
}

query TasksViewTable($where: TaskWhereInput, $orderBy: [TaskOrderByWithRelationInput!], $cursor: TaskWhereUniqueInput, $take: Int, $skip: Int, $distinct: [TaskScalarFieldEnum!]) {
  tasks(where: $where, orderBy: $orderBy, cursor: $cursor, take: $take, skip: $skip, distinct: $distinct) {
    _count {
      prompts
      tips
    }
    category {
      name
      id
    }
    createdAt
    imoji
    name
    slug
    tags
    id
  }
}


query AggregateTask($where: TaskWhereInput, $cursor: TaskWhereUniqueInput) {
  aggregateTask(where: $where, cursor: $cursor) {
    _count {
      _all
    }
  }
}

  query Task($where: TaskWhereUniqueInput!) {
  task(where: $where) {
       slug
    tags

    description
    createdAt
   
    id
    imoji
    name
    updatedAt
    categoryId
    prompts {
      description
      id
      name
    }
        tips {
      id
      description
    }
     category {
      name
      
    }
 
  }
}


mutation CreateOneTask($data: TaskCreateInput!) {
  createOneTask(data: $data) {
    id
  }
}
mutation DeleteOneTask($where: TaskWhereUniqueInput!) {
  deleteOneTask(where: $where) {
    id
  }
}
mutation UpdateOneTask($data: TaskUpdateInput!, $where: TaskWhereUniqueInput!) {
  updateOneTask(data: $data, where: $where) {
    id
  }
}

mutation UpdateManyTask($data: TaskUpdateManyMutationInput!, $where: TaskWhereInput) {
  updateManyTask(data: $data, where: $where) {
    count
  }
}